services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mcp-nosql
    container_name: mongo_seeding
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    command: ["seed.py"]

  mcp-sql:
    build: ./mcp-sql
    container_name: mcp_sql_service
    volumes:
      - ../../Chinook.sqlite:/Chinook.sqlite
    command: ["mcp_sql_server.py"]

  mcp-nosql:
    build: ./mcp-nosql
    container_name: mcp_nosql_service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    command: ["mcp_nosql_server.py"]